name: Pull Request Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - review_requested

concurrency:
  group: ${{ github.workflow }}/PR-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ ! github.event.pull_request.draft }}
    uses: ./.github/workflows/build.yml

  test_simple:
    concurrency:
      group: ${{ github.ref }} - tests
      cancel-in-progress: true
    needs: build
    if: ${{ ! github.event.pull_request.draft && github.event.pull_request.requested_reviewers[0] == null }}
    uses: ./.github/workflows/code_test.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      artifact-run-id: ${{ needs.build.outputs.run-id }}

  test_full:
    needs: build
    concurrency:
      group: ${{ github.ref }} - tests
      cancel-in-progress: true
    if: &reviewers_condition ${{ ! github.event.pull_request.draft && github.event.pull_request.requested_reviewers[0] != null }}
    uses: ./.github/workflows/code_test.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      artifact-run-id: ${{ needs.build.outputs.run-id }}
      test-all-versions: true

  docs_build:
    concurrency:
      group: ${{ github.ref }} - docs
      cancel-in-progress: true
    permissions:
      pages: write     # to deploy to GitHub Pages
      id-token: write  # to verify the deployment
    if: *reviewers_condition
    uses: ./.github/workflows/docs_build.yml
